// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvQnX4wdPFv7cP_pmy31HDoEYfIF0L4CA',
    appId: '1:997487204878:web:9c94f06a222e82d0eb7a5f',
    messagingSenderId: '997487204878',
    projectId: 'tody-app-6dbde',
    authDomain: 'tody-app-6dbde.firebaseapp.com',
    storageBucket: 'tody-app-6dbde.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9d6zamNy7sIKxFM3MpDr17w_t5UP0spc',
    appId: '1:997487204878:android:5a26d63fda26e59eeb7a5f',
    messagingSenderId: '997487204878',
    projectId: 'tody-app-6dbde',
    storageBucket: 'tody-app-6dbde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA337wkr1ujwIvv2tiSQsDHy3pJgBeBI2s',
    appId: '1:997487204878:ios:18d2943ed422d30deb7a5f',
    messagingSenderId: '997487204878',
    projectId: 'tody-app-6dbde',
    storageBucket: 'tody-app-6dbde.firebasestorage.app',
    androidClientId: '997487204878-dsratdd9p3n2qa8q4dqf2k9s16l9cr8b.apps.googleusercontent.com',
    iosClientId: '997487204878-4m6v2drskv8h0pg3dkou1oir602ksadh.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA337wkr1ujwIvv2tiSQsDHy3pJgBeBI2s',
    appId: '1:997487204878:ios:18d2943ed422d30deb7a5f',
    messagingSenderId: '997487204878',
    projectId: 'tody-app-6dbde',
    storageBucket: 'tody-app-6dbde.firebasestorage.app',
    androidClientId: '997487204878-dsratdd9p3n2qa8q4dqf2k9s16l9cr8b.apps.googleusercontent.com',
    iosClientId: '997487204878-4m6v2drskv8h0pg3dkou1oir602ksadh.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvQnX4wdPFv7cP_pmy31HDoEYfIF0L4CA',
    appId: '1:997487204878:web:1c9299c2581ec85eeb7a5f',
    messagingSenderId: '997487204878',
    projectId: 'tody-app-6dbde',
    authDomain: 'tody-app-6dbde.firebaseapp.com',
    storageBucket: 'tody-app-6dbde.firebasestorage.app',
  );

}